config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign_in' => 'authentications#new', as: :signin
  post '/sign_in' => 'authentications#create'
  get '/sign_out' => 'authentications#destroy', as: :signout

  resources :weddings do
    resources :events
  end

  resources :vendors do
    resources :budgets, except: [:index]
  end

  resources :budgets, only: [:index]

  resources :budgets, only:[] do
    resources :payments, except: [:show]
  end
end

app/models/budget.rb
class Budget<ActiveRecord::Base
  belongs_to :vendor
  belongs_to :user
  has_many :payments, dependent: :destroy

  monetize :total_due
end

app/models/event.rb
class Event<ActiveRecord::Base
  belongs_to :wedding
  belongs_to :vendor
end

app/models/payment.rb
class Payment<ActiveRecord::Base
  validate :not_past_date
  belongs_to :budget

  def not_past_date
    if self.due_date && self.due_date.past?
      self.errors.add(:due_date, "can't be in the past")
    end
  end
end

app/models/user.rb
class User<ActiveRecord::Base
  has_secure_password

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :vendors, :through => :vendors
  has_many :budgets
  has_one :wedding

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  validates :name, presence: true
  validates :phone_number, presence: true
  validates :contact_person, presence: true
  validates :contact_email, presence: true

  has_many :budgets, dependent: :destroy
  has_many :users, through: :budgets
  has_many :events

end

app/models/wedding.rb
class Wedding<ActiveRecord::Base
  has_many :events
  has_many :vendors, through: :events
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user

  def authenticate
    unless current_user
      flash[:danger] = 'You must sign in'
      redirect_to signin_path
    end
  end

  def payments_sum
    @budget.payments.reduce(0) { |sum, payment| sum + (payment.paid ? payment.amount : 0) }
    # condition ? trueval : falseval
  end

  helper_method :payments_sum

  def budgets_sum
    current_user.budgets.reduce(0) { |sum, payment| sum + payment.total_due }
  end

  helper_method :budgets_sum

end

app/controllers/authentications_controller.rb
class AuthenticationsController <ApplicationController

  def create
    user = User.find_by(:email => params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully signed in"
      if current_user.wedding
        redirect_to wedding_path(current_user.wedding)
      else
        redirect_to root_path
      end
    else
      @sign_in_error = "Email / Password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:success] = "You have successfully logged out"
    redirect_to root_path
  end

end

app/controllers/budgets_controller.rb
class BudgetsController<ApplicationController
  before_action :set_user
  before_action :set_vendor, except: [:index]

  def index
    @budgets = Budget.all
  end

  def new
    @budget = Budget.new
  end

  def create
    @budget = Budget.new(budget_params.merge(vendor_id: params[:vendor_id]))
    @budget.user_id = current_user.id
    if @budget.save(budget_params)
      redirect_to vendor_budget_path(@vendor, @budget)
    else
      render :new
    end
  end

  def show
    @budget = Budget.find(params[:id])
    @payment = Payment.new
  end

  def edit
    @budget = Budget.find(params[:id])
  end

  def update
    @budget = Budget.find(params[:vendor_id])
    if @budget.update(budget_params)
      redirect_to vendor_budgets_path
      flash[:success] = "#{@vendor.name} budget was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    Budget.find(params[:id]).destroy
    flash[:success] = "#{@vendor.name}'s quote was successfully deleted."
    redirect_to budgets_path
  end

  private

  def set_vendor
    @vendor = Vendor.find_by(id: params[:vendor_id])
  end

  def set_user
    @user = current_user
  end

  def budget_params
    params.require(:budget).permit(:vendor_id, :total_due, :down_payment, :additional_payments, :user_id, :bank_website)
  end

end

app/controllers/events_controller.rb
class EventsController<ApplicationController
  before_action :authenticate
  before_action :set_wedding

  def create
    @event = Event.new(event_params.merge(wedding_id: params[:wedding_id]))
    if @event.save(event_params)
      redirect_to wedding_path(@wedding)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to wedding_path(@wedding)
    else
      render :edit
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to wedding_path(@wedding)
    flash[:success] = "Event was successfully deleted"
  end

  private

  def event_params
    params.require(:event).permit(:location, :date, :start_time, :notes, :wedding_id, :vendor_id, :name)
  end

  def set_wedding
    @wedding = Wedding.find(params[:wedding_id])
  end
end

app/controllers/payments_controller.rb
class PaymentsController<ApplicationController
  before_action :set_budget

  def create
    @payment = Payment.new(payment_params.merge(budget_id: params[:budget_id]))
    if @payment.save
      redirect_to vendor_budget_path(vendor_id:@budget.vendor_id, id:@budget.id)
    else
      redirect_to budgets_path(@budget)
    end
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.find(params[:id])
    if @payment.update(payment_params)
      redirect_to vendor_budget_path(vendor_id: @budget.vendor_id, id:@budget.id)
    else
      render :edit
    end
  end

  def destroy
    Payment.find(params[:id]).destroy
    flash[:success] = 'Payment was successfully deleted'

    redirect_to vendor_budget_path(vendor_id: @budget.vendor_id, id:@budget.id)
  end

  private

  def set_budget
    @budget = Budget.find(params[:budget_id])
  end

  def payment_params
    params.require(:payment).permit(:budget_id, :due_date, :amount, :paid)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController<ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password, :password_confirmation, :bank_website))
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You have successfully signed up"
      redirect_to root_path
    else
      render :new
    end
  end

end

app/controllers/vendors_controller.rb
class VendorsController <ApplicationController
  before_action :set_user

  def index
    @vendors = Vendor.all
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save

      redirect_to vendor_path(@vendor)

    else
      render :new

    end
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])
    if @vendor.update(vendor_params)

      redirect_to vendor_path(vendor_params)

    else
      render :edit
    end
  end

  def destroy
    vendor = Vendor.find(params[:id])
    vendor.destroy

    redirect_to vendors_path
  end

  private

  def vendor_params
    params.require(:vendor).permit(:name, :phone_number, :contact_person, :contact_email, :additional_info)
  end

  def set_user
    @user = current_user
  end

end

app/controllers/weddings_controller.rb
class WeddingsController<ApplicationController

  def new
    @wedding = Wedding.new
  end

  def create
    @wedding = Wedding.new
    @wedding.user_id = current_user.id
    if @wedding.save(wedding_params)
      redirect_to wedding_path(@wedding)
    else
      render :new
    end
  end

  def show
    @wedding = Wedding.find(params[:id])
    @event = Event.new
    @events_by_day = @wedding.events.order(date: :asc, start_time: :asc).group_by { |event| event.date.strftime("%b %d %Y") }
  end

  private

  def wedding_params
    params.require(:wedding).permit(:user_id, :name)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController<ApplicationController
  before_action :authenticate
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentications/new.html.erb
Please Sign In

<%= form_tag signin_path do %>

  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Sign In" %>

<% end %>

app/views/budgets/_form.html.erb
<%= form_for ([@vendor, @budget]) do |f| %>

  <%= f.label :total_due %>
  <%= f.number_field :total_due %>

  <%= f.label :bank_website, "Add a Bank Website for Easy Payments" %>
  <%= f.text_field :bank_website %>

  <%= f.submit "#{name_of_button} Quote" %>

<% end %>

<%= link_to "Cancel", vendor_path(@vendor), class: 'btn btn-default' %>

app/views/budgets/edit.html.erb
Edit Budget

<%= render partial: "form", locals: {name_of_button: "Update"} %>

app/views/budgets/index.html.erb
<div class= 'page-header'>
  <p><h1><%= "Wedding Budget for #{current_user.username}" %> <%= link_to "Add a New Vendor",new_vendor_path, class:"btn btn-info pull-right" %></h1></p>
</div>

<table class="table">
  <thead>
    <th>Vendor Name</th>
    <th>Vendor Quote</th>
    <th></th>
  </thead>
<% current_user.budgets.each do |budget| %>
  <tbody>
    <td><%= link_to "#{budget.vendor.name}", vendor_path(budget.vendor.id) %></td>
    <td><%= link_to "$#{budget.total_due}", vendor_budget_path(budget.vendor.id, budget)%></td>
    <td>
      <%= link_to "Add Vendor Quote", new_vendor_budget_path(budget.vendor.id), class: "btn btn-info"%>
      <%= link_to "Delete Quote", vendor_budget_path(budget.vendor.id, budget), method: :delete, class: "btn btn-info"%>
    </td>
  </tbody>
<% end %>
</table>

<h5><%= "Total Wedding Budget: $#{budgets_sum}" %></h5>

app/views/budgets/new.html.erb
<%= "New Budget" %>

<%= render partial: "form", locals: {name_of_button: "Create"} %>

app/views/budgets/show.html.erb
<div class= 'page-header'>
  <p>
    <h1>
      <%= "#{@budget.vendor.name} Quote" %>
      <div class="pull-right">
        <%= link_to "Edit Quote", edit_vendor_budget_path(@vendor, @budget), class:"btn btn-info" %><%= link_to "Delete",vendor_budget_path(@vendor, @budget), method: :delete, class: "btn btn-danger"%><%= link_to 'Back', vendor_path(@vendor), class: "btn btn-default" %>
      </div>
    </h1>
  </p>
</div>

<h4><%= "Total Due: $#{@budget.total_due}" %></h4>


<div class= "well">
  <h4>Add a Payment:</h4>
    <%= form_for [@budget, @payment], html: {class: "form-group"} do |f| %>
      <div class= "row">
        <div class= "col-md-2">
          <%= f.label :amount %>
          <%= f.number_field :amount, class: "form-control" %>
        </div>
        <div class= "col-md-2">
          <%= f.label :due_date %>
          <%= f.date_field :due_date, class: "form-control" %>
        </div>
      </div>
        <%= f.submit "Add Payment", class: "btn btn-primary" %>
    <%end%>
</div>

<h3>Payments:</h3>
<table class="table">
  <thead>
    <th>Payment Amount</th>
    <th>Payment Due Date</th>
    <th>Payment Status</th>
    <th></th>
    <th></th>
  </thead>

    <% if @budget.payments %>
      <% @budget.payments.each do |payment| %>
      <tbody>
        <td><%= "$ #{payment.amount}" %></td>
        <% if payment.due_date %>
          <td><%= payment.due_date.strftime( "%m/%d/%Y" ) %></td>
        <% else %>
          <td><%= payment.due_date %></td>
        <% end %>

        <% if payment.paid %>
          <td><%= "PAID" %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to "Edit", edit_budget_payment_path(budget_id:payment.budget_id, id: payment.id) %></td>
        <td><%= link_to "Delete", budget_payment_path(budget_id:payment.budget_id, id: payment.id), method: :delete %></td>
      <% end %>
    </tbody>
    <% end %>

</table>
<h4><%= "#{@budget.vendor.name} Quote Balance:"%> <%= "$#{@budget.total_due-payments_sum}" %></h4>

<h4><%= link_to("Make a Payment", @budget.bank_website) %></h4>

app/views/events/edit.html.erb
<div class= "well">
  <h4>Edit Your Event:</h4>
  <%= form_for [@wedding, @event], html: {class: "form-group"} do |f| %>
  <div class= "row">
    <div class= "col-md-2">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class= "col-md-2">
      <%= f.label :date %>
      <%= f.date_field :date, class: "form-control" %>
    </div>
    <div class= "col-md-2">
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>
    <div class= "col-md-2">
      <%= f.label :start_time %>
      <%= f.time_field :start_time, class: "form-control" %>
    </div>
    <div class= "col-md-4">
      <%= f.label :vendor_id, "Vendor" %>
      <%= f.collection_select(:vendor_id, Vendor.all, :id, :name, {prompt: "Please select a vendor..."}, {class:'form-control'}) %>
    </div>
    <div class= "col-md-6">
      <%= f.label :notes %>
      <%= f.text_area :notes, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Update Event", class: "btn btn-primary" %>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeddingEventPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<nav class='navbar navbar-inverse navbar-fixed-top'>
  <div class='container'>
    <% if current_user != nil && current_user.wedding %>
      <%= link_to "Wedding Event Planner", wedding_path(current_user.wedding), class: "navbar-brand" %>
    <% else %>
     <a class='navbar-brand' href='/'>Wedding Event Planner</a>
    <% end %>
    <ul class="nav navbar-nav">
      <% if current_user != nil && current_user.wedding %>
        <li><%= link_to "Events", wedding_path(current_user.wedding) %></li>
      <% else %>
        redirect_to root_path
        flash[:danger] = "You must create a wedding"
      <% end %>
      <li><a href="/vendors">Vendors</a></li>
      <li><a href="/budgets">Budget</a></li>
    </ul>
    <div class= 'pull-right'>
      <% if current_user %>
      <%= link_to "#{current_user.username}", root_path, class: 'navbar-text' %>
      <%= link_to "Sign Out", signout_path, class: 'navbar-text' %>
      <% else %>
      <%= link_to "Sign Up", signup_path, class: 'navbar-text' %>
      <%= link_to "Sign In", signin_path, class: 'navbar-text' %>
      <% end %>
    </div>
  </div>
</nav>

<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}", class: 'alert alert-success' %>
<% end %>

<body>
  <div class= "container">
    <%= yield %>
  </div>
</body>
</html>

app/views/payments/edit.html.erb
<%= form_for [@budget, @payment], html: {class: "form-group"} do |f| %>
<p>
  <div class= "row">
    <div class= "col-md-2">
      <%= f.label :amount %>
      <%= f.number_field :amount, class: "form-control" %>
    </div>
    <div class= "col-md-2">
      <%= f.label :due_date %>
      <%= f.date_field :due_date, class: "form-control" %>
    </div>

    <div class= 'form-group'>
      <div class= 'col-sm-offset-2 col-sm-10'>
        <div class= 'checkbox'>
          <label>
            <%= f.check_box :paid %> Paid
          </label>
        </div>
      </div>
    </div>

    <%= f.submit "Update Payment", class: "btn btn-primary" %>
  </div>
</p>
<%end%>

<%= link_to "Cancel", budgets_path, class: 'btn btn-default' %>

app/views/vendors/_form.html.erb
<%= form_for @vendor do |f| %>

  <%= f.error_messages %>

  <%= f.label :name%>
  <%= f.text_field :name%>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :contact_person %>
  <%= f.text_field :contact_person %>

  <%= f.label :contact_email %>
  <%= f.text_field :contact_email %>

  <%= f.label :additional_info %>
  <%= f.text_field :additional_info %>

  <%= f.submit "#{name_of_button} Vendor" %>
  <%= link_to "Cancel", vendors_path %>

<%end%>

app/views/vendors/edit.html.erb
<h1>Edit Vendor</h1>

<%= render partial: "form", locals:{name_of_button: "Update"} %>

app/views/vendors/index.html.erb
<div class= 'page-header'>
  <p><h1><%= "Wedding Vendors for #{current_user.username}" %> <%= link_to "New Vendor", new_vendor_path(@vendor), class:"btn btn-info pull-right" %></h1></p>
</div>

<table class="table">
  <thead>
    <th> Vendor Name </th>
    <th> Phone Number </th>
    <th> Contact </th>
    <th> Email </th>
    <th> Notes </th>
  </thead>

  <% @vendors.each do |vendor| %>
    <tbody>
      <td><%= link_to vendor.name, vendor_path(vendor) %></td>
      <td><%= vendor.phone_number %></td>
      <td><%= vendor.contact_person %></td>
      <td><%= vendor.contact_email %></td>
      <td><%= vendor.additional_info %></td>
    </tbody>
  <%end%>
</table>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render partial: "form", locals: {name_of_button: "Create"} %>

app/views/vendors/show.html.erb
<div class= 'page-header'>
  <p><h1><%= "#{@vendor.name}" %> <%= link_to "Add Quote", new_vendor_budget_path(@vendor), class:"btn btn-info pull-right" %></h1></p>
</div>

<table class="table">
  <thead>
    <th> Phone Number </th>
    <th> Contact </th>
    <th> Email </th>
    <th> Notes </th>
    <th></th>

  </thead>
  <tbody>
    <td><%= @vendor.phone_number %></td>
    <td><%= @vendor.contact_person %></td>
    <td><%= @vendor.contact_email %></td>
    <td><%= @vendor.additional_info %></td>

    <td><%= link_to 'Edit', edit_vendor_path(@vendor), class: 'btn btn-info'%>
    <%= link_to 'Delete', vendor_path(@vendor), method: :delete, class: 'btn btn-danger' %>
    <%= link_to 'Back', vendors_path, class: "btn btn-default" %></td>
  </tbody>
</table>


<table class= 'table'>
  <thead>
    <th>Quotes:</th>
  </thead>
    <% if @vendor.budgets %>
    <% @vendor.budgets.each do |quote| %>
      <tbody>
        <td><%= link_to "$#{quote.total_due} Quote Info", vendor_budget_path(vendor_id:quote.vendor_id, id:quote.id) %></td>
      </tbody>
    <% end %>
  <% end %>
</table>

<br>
<br>
<br>
<br>
<% if @vendor.name && @vendor.name == 'Love in Bloom' %>
  <div class= "text-center">
    <a data-pin-do="embedBoard" href="http://www.pinterest.com/katie1pekarek/love-in-bloom/" data-pin-scale-width="200" data-pin-scale-height="420" data-pin-board-width="600">Follow Katie Pekarek's board Wedding Flowers on Pinterest.</a>
    <!-- Please call pinit.js only once per page -->
    <script type="text/javascript" async defer src="//assets.pinterest.com/js/pinit.js"></script>
  </div>
<% end %>

app/views/weddings/new.html.erb
<%= form_for @wedding do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Create Wedding", class: "btn btn-info" %>
  
<% end %>

app/views/weddings/show.html.erb
<h1><%= "#{@wedding.name} Wedding Info" %></h1>

<div class= "well">
  <h4>Add an Event:</h4>
  <%= form_for [@wedding, @event], html: {class: "form-group"} do |f| %>
  <div class= "row">
    <div class= "col-md-2">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class= "col-md-2">
      <%= f.label :date %>
      <%= f.date_field :date, class: "form-control" %>
    </div>
    <div class= "col-md-2">
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>
    <div class= "col-md-2">
      <%= f.label :start_time %>
      <%= f.time_field :start_time, class: "form-control" %>
    </div>
    <div class= "col-md-4">
      <%= f.label :vendor_id, "Vendor" %>
      <%= f.collection_select(:vendor_id, Vendor.all, :id, :name, {prompt: "Please select a vendor..."}, {class:'form-control'}) %>
    </div>
    <div class= "col-md-6">
      <%= f.label :notes %>
      <%= f.text_area :notes, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Add Event", class: "btn btn-primary" %>
  <%end%>
</div>

<h3><%= "#{@wedding.name} Events:" %></h3>
  <% if @wedding.events %>
    <% @events_by_day.each do |day, event| %>
      <h4><%= day %></h4>
      <table class="table">
        <thead>
          <th>Name</th>
          <th>Location</th>
          <th>Start Time</th>
          <th>Notes</th>
          <th>Vendor</th>
          <th></th>
          <th></th>
        </thead>
        <% event.each do |event| %>
          <tbody>
            <td><%= event.name %></td>

            <td><%= event.location %></td>

            <% if event.start_time %>
              <td><%= event.start_time.strftime( "%l:%M %p" ) %></td>
            <% else %>
              <td><%= event.start_time %></td>
            <% end %>

            <td><%= event.notes %></td>

            <% if event.vendor %>
              <td><%= link_to "#{event.vendor.name}", vendor_path(event.vendor.id)%></td>
            <% else %>
              <td></td>
            <% end %>
            <td><%= link_to "Edit", edit_wedding_event_path(wedding_id:event.wedding_id, id: event.id) %></td>
            <td><%= link_to "Delete", wedding_event_path(wedding_id:event.wedding_id, id: event.id), method: :delete %></td>
          </tbody>
        <% end %>
      </table>
    <% end %>
  <% end %>

app/views/welcome/index.html.erb
<div class='jumbotron'>
  <h1>Wedding Event Planner</h1>
  <p>Let's get started: <%= link_to "Create Wedding", new_wedding_path %><p>
</div>